import { FarresProjectModel } from './farres-project-model';

export const ProjectItems: FarresProjectModel[] = [
    {
        id: 1,
        type: 'Quiz 1',
        projectname: 'HTML Quiz',
        notes: 'Quiz',
        startdate: new Date (2019, 2, 28),
        status: 'complete',
      },
      {
        id: 2,
        type: "Project",
        projectname: "Module 1 Project 1",
        notes: "Angular",
        startdate: new Date (2019, 3, 5),
        status: "Complete",
      },
      {
        id: 3,
        type: "HW",
        projectname: "Module 1 HW 1",
        notes: "Angular",
        startdate: new Date (2019, 3, 10),
        status: "Complete",
      },
      {
        id: 4,
        type: "Home",
        projectname: "Dishes",
        notes: "Clean all the dishes",
        startdate: new Date (2019, 2, 28),
        status: "Active",
      },
      {
        id: 5,
        type: "Home",
        projectname: "Paint room",
        notes: "Buy paint first",
        startdate: new Date (2019, 3, 27),
        status: "Active",
      },
      {
        id: 6,
        type: "Travel",
        projectname: "Vist Home",
        notes: "Buy Ticket",
        startdate: new Date (2019, 4, 27),
        status: "Pending",
      },
      {
        id: 7,
        type: "Project",
        projectname: "Group Project 1",
        notes: "Agree on meeting time",
        startdate: new Date (2019, 2, 27),
        status: "Pending",
      },
      {
        id: 8,
        type: "Home",
        projectname: "Take out trash",
        notes: "Buy trash bags",
        startdate: new Date (2019, 2, 27),
        status: "Pending",
      },
      {
        id: 9,
        type: "Shopping",
        projectname: "Buy Shoes",
        notes: "Use Deal",
        startdate: new Date (2019, 3, 15),
        status: "Active",
      },
      {
        id: 10,
        type: "Shopping",
        projectname: "Buy Laptop Charger",
        notes: "Use Amazon Prime",
        startdate: new Date (2019, 2, 27),
        status: "Completed",
      },
]